apiVersion: v1
kind: Service
metadata:
  name: taskflow-service
  namespace: taskflow-staging
spec:
  type: NodePort
  selector:
    app: taskflow
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007